# Generated by Django 5.0.14 on 2026-07-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HungryHub Gourmet', max_length=255)),
                ('tagline', models.CharField(default='100% Pure Vegetarian Restaurant & Dining', max_length=255)),
                ('address', models.TextField(default='Near Commerce Six Roads, Navrangpura, Ahmedabad, Gujarat 380009')),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('email', models.EmailField(default='info@hungryhub.com', max_length=254)),
                ('opening_time', models.CharField(default='11:00 AM', max_length=50)),
                ('closing_time', models.CharField(default='11:00 PM', max_length=50)),
                ('delivery_charges', models.DecimalField(decimal_places=2, default=7.0, max_digits=10)),
                ('free_delivery_limit', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('gst_number', models.CharField(default='24AAACH1111A1Z1', max_length=50)),
                ('logo', models.CharField(blank=True, default='https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=400', max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('super_admin', 'Super Admin'), ('manager', 'Manager'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
    ]
