# Generated by Django 5.0.14 on 2026-07-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_restaurantsettings_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsettings',
            name='delivery_charges',
        ),
        migrations.RemoveField(
            model_name='restaurantsettings',
            name='free_delivery_limit',
        ),
    ]
