# Generated by Django 5.0.14 on 2026-07-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_user',
        ),
    ]
