# Generated by Django 5.0.14 on 2026-07-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_user',
        ),
    ]
