# Generated by Django 5.0.14 on 2026-07-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='orders_cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='orders_cartitem',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='orders_orderitem',
        ),
    ]
