# Generated by Django 5.0.14 on 2026-07-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday Celebration'), ('anniversary', 'Anniversary Celebration'), ('other', 'Other Functions & Events')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('per_person', 'Per Person'), ('fixed', 'Fixed')], max_length=20)),
                ('min_capacity', models.PositiveIntegerField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('inclusions', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('booking_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('table_type', models.CharField(max_length=50)),
                ('table_number', models.CharField(max_length=50)),
                ('guests_count', models.PositiveIntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default='Paid', max_length=50)),
                ('reservation_status', models.CharField(default='Confirmed', max_length=50)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.package')),
            ],
        ),
    ]
