# Generated by Django 5.0.14 on 2026-07-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(default='4 Hours', max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday Celebration'), ('anniversary', 'Anniversary Celebration'), ('corporate', 'Corporate Party'), ('family', 'Family Celebration'), ('other', 'Other Functions & Events')], max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='min_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
