# Generated by Django 5.0.14 on 2026-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_package_description_package_image_package_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='invoice_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
