# Generated by Django 5.0.14 on 2026-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_email_sent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email_sent_status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], default='Failed', max_length=10),
        ),
    ]
