# Generated by Django 5.0.14 on 2026-07-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_package_created_at_package_image_package_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='last_email_attempt_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
