# Generated by Django 5.0.14 on 2026-07-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner_image', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percent', models.IntegerField(default=10)),
                ('promo_code', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('applicable_category', models.CharField(default='All', max_length=100)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('terms', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
