# Generated by Django 5.0.14 on 2026-07-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_banner_offer_usage_count_offer_usage_limit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='Coupon',
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('homepage', 'Homepage Banner'), ('coupons', 'Coupons Banner'), ('festival', 'Festival Banner')], default='homepage', max_length=20),
        ),
    ]
