# Generated by Django 5.0.14 on 2026-07-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_rename_offer_coupon_alter_banner_banner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='banner_image',
        ),
    ]
