# Generated by Django 5.0.14 on 2026-07-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
