export const categories = [
  {
    name: "Cold Beverage",
    slug: "cold-beverage",
    image: "/Cold Beverage.jpg",
    route: "/menu?category=cold-beverage"
  },
  {
    name: "Hot Beverage",
    slug: "hot-beverage",
    image: "/Hot Beverage.jpg",
    route: "/menu?category=hot-beverage"
  },
  {
    name: "Mocktails",
    slug: "mocktails",
    image:  "/Mocktails.jpg",   
    route: "/menu?category=mocktails"
  },
  {
    name: "Steaming Soup",
    slug: "steaming-soup",
    image: "/Steaming Soup.jpg" ,
    route: "/menu?category=steaming-soup"
  },
  {
    name: "Yummy Pizza",
    slug: "yummy-pizza",
    image: "/Yummy Pizza.jpg",    
    route: "/menu?category=yummy-pizza"
  },
  {
    name: "Bread & Burger",
    slug: "bread-burger",
    image: "/Bread & Burger.jpg",    
    route: "/menu?category=bread-burger"
  },
  {
    name: "Snacks",
    slug: "snacks",
    image: "/Snacks.jpg",
    route: "/menu?category=snacks"
  },
  {
    name: "Sandwiches",
    slug: "sandwiches",
    image: "/Sandwiches.jpg",    
    route: "/menu?category=sandwiches"
  },
  {
    name: "Baked Dish",
    slug: "baked-dish",
    image:"/Baked Dish.jpg",     
    route: "/menu?category=baked-dish"
  },
  {
    name: "Italian Pastas",
    slug: "italian-pastas",
    image: "/Italian Pastas.jpg",
    route: "/menu?category=italian-pastas"
  },
  {
    name: "Chinese Cuisine Starters",
    slug: "chinese-cuisine-starters",
    image: "/Chinese Cuisine Starters.jpg",    
    route: "/menu?category=chinese-cuisine-starters"
  },
  {
    name: "Chinese Cuisine Main Course",
    slug: "chinese-cuisine-main-course",
    image:  "/Chinese Cuisine Main Course.jpg",   
    route: "/menu?category=chinese-cuisine-main-course"
  },
  {
    name: "Sizzler",
    slug: "sizzler",
    image:"/Sizzler.jpg",     
    route: "/menu?category=sizzler"
  },
  {
    name: "Paneer Ka Khazana",
    slug: "paneer-ka-khazana",
    image: "/Paneer Ka Khazana.jpg",    
    route: "/menu?category=paneer-ka-khazana"
  },
  {
    name: "Kofta Ka Kamal",
    slug: "kofta-ka-kamal",
    image: "/Kofta Ka Kamal.jpg",    
    route: "/menu?category=kofta-ka-kamal"
  },
  {
    name: "Cheese Ka Khazana",
    slug: "cheese-ka-khazana",
    image:"/Cheese Ka Khazana.jpg",   
    route: "/menu?category=cheese-ka-khazana"
  },
  {
    name: "Indian Main Course",
    slug: "indian-main-course",
    image:"/Indian Main Course.jpg",    
    route: "/menu?category=indian-main-course"
  },
  {
    name: "Indian Bread",
    slug: "indian-bread",
    image:"/Indian Bread.jpg",    
    route: "/menu?category=indian-bread"
  },
  {
    name: "Dal Ke Diwane",
    slug: "dal-ke-diwane",
    image: "/Dal Ke Diwane.jpg",   
    route: "/menu?category=dal-ke-diwane"
  },
  {
    name: "Basmati Ka Khazana",
    slug: "basmati-ka-khazana",
    image: "/Basmati Ka Khazana.jpg",    
    route: "/menu?category=basmati-ka-khazana"
  },
  {
    name: "Kaju Ki Peshkash",
    slug: "kaju-ki-peshkash",
    image: "/Kaju Ki Peshkash.jpg" ,  
    route: "/menu?category=kaju-ki-peshkash"
  },
  {
    name: "Special Soya Chaap",
    slug: "special-soya-chaap",
    image: "/Special Soya Chaap.jpg",   
    route: "/menu?category=special-soya-chaap"
  },
  {
    name: "Tandoor Ke Sholay",
    slug: "tandoor-ke-sholay",
    image: "/Tandoor Ke Sholay.jpg",    
    route: "/menu?category=tandoor-ke-sholay"
  },
  {
    name: "Choice of Lassi",
    slug: "choice-of-lassi",
    image: "/Choice of Lassi.jpg",     
    route: "/menu?category=choice-of-lassi"
  },
  {
    name: "Dahi Ka Swad",
    slug: "dahi-ka-swad",
    image: "/Dahi Ka Swad.jpg",   
    route: "/menu?category=dahi-ka-swad"
  },
  {
    name: "Papads",
    slug: "papads",
    image:"/Papads.jpg",   
    route: "/menu?category=papads"
  },
  {
    name: "Appetizer Salad",
    slug: "appetizer-salad",
    image:"/Appetizer Salad.jpg",   
    route: "/menu?category=appetizer-salad"
  },
  {
    name: "Smoothie",
    slug: "smoothie",
    image:"/Smoothie.jpg",    
    route: "/menu?category=smoothie"
  },
  {
    name: "Chef Special Shake",
    slug: "chef-special-shake",
    image:"/Chef Special Shake.jpg",    
    route: "/menu?category=chef-special-shake"
  },
  {
    name: "Shots",
    slug: "shots",
    image:"/Shots.jpg",     
    route: "/menu?category=shots"
  },
  {
    name: "Desserts",
    slug: "desserts",
    image:"/Desserts.jpg",     
    route: "/menu?category=desserts"
  },
  {
    name: "Sweets",
    slug: "sweets",
    image:"/Sweets.jpg",    
    route: "/menu?category=sweets"
  }
];

export const mockMenuItems = [
  // Cold Beverage
  {
    id: "cb-1",
    name: "Mineral Water",
    category: "cold-beverage",
    price: 30,
    approx_qty_gms: 300,
  },
  {
    id: "cb-2",
    name: "Soft drinks",
    category: "cold-beverage",
    price: 40,
    approx_qty_gms: 300,
  },
  {
    id: "cb-3",
    name: "Fresh lemon water",
    category: "cold-beverage",
    price: 50,
    approx_qty_gms: 300,
    description: "Sweet/salted",
  },
  {
    id: "cb-4",
    name: "Fresh lime soda",
    category: "cold-beverage",
    price: 80,
    approx_qty_gms: 300,
    description: "Sweet/Salted",
  },
  {
    id: "cb-5",
    name: "Cold coffee",
    category: "cold-beverage",
    price: 189,
    approx_qty_gms: 300
  },
  {
    id: "cb-6",
    name: "Cold coffee with ice cream",
    category: "cold-beverage",
    price: 229,
    approx_qty_gms: 300,
  },
  {
    id: "cb-7",
    name: "Lemon ice tea",
    category: "cold-beverage",
    price: 149,
    approx_qty_gms: 300,
  },
  // Hot Beverage
  {
    id: "hb-1",
    name: "Masala Chai",
    category: "hot-beverage",
    price: 40,
    approx_qty_gms: 200,
    
  },
  {
    id: "hb-2",
    name: "Hot Coffee",
    category: "hot-beverage",
    price: 50,
    approx_qty_gms: 200,
  },
  {
    id: "hb-3",
    name: "Green tea",
    category: "hot-beverage",
    price: 90,
    approx_qty_gms: 200,
  },
  {
    id: "hb-4",
    name: "Hazelnut Delight",
    category: "hot-beverage",
    price: 189,
    approx_qty_gms: 200,
   
  },
  {
    id: "hb-5",
    name: "Espresso",
    category: "hot-beverage",
    price: 109,
    approx_qty_gms: 200,
    
  },
  // Mocktails
  {
    id: "mc-1",
    name: "Watermelon Mojito",
    category: "mocktails",
    price: 180,
    approx_qty_gms: 350,
    description: "Lemon, watermelon syrup, mint"
  },

  {
    id: "mc-2",
    name: "Ruby lime",
    category: "mocktails",
    price: 210,
    approx_qty_gms: 350,
  },
  {
    id: "mc-3",
    name: "Skin Shine",
    category: "mocktails",
    price: 199,
    approx_qty_gms: 350,
    description:"Carrot, beetroot, cucumber, ginger"
  },
  {
    id: "mc-4",
    name: "Cool Sky",
    category: "mocktails",
    price: 210,
    approx_qty_gms: 350,
    description:"Orange , pineapple, strawberry"
  },
  {
    id: "mc-5",
    name: "Kiwi colada",
    category: "mocktails",
    price: 210,
    approx_qty_gms: 350,
    description:"Pineapple juice, kiwi crush, coconut milk"
  },
  

  // Steaming Soup
  {
    id: "ss-1",
    name: "Tamatar Dhania Shorba",
    category: "steaming-soup",
    price: 140,
    approx_qty_gms: 250,
    description: "A light tomato soup flavored with fresh coriander, ginger, and hand-ground cumin.",
  },
  {
    id: "ss-2",
    name: "Hot & Sour Veg Soup",
    category: "steaming-soup",
    price: 150,
    approx_qty_gms: 250,
    description: "Spicy and tangy Chinese soup loaded with minced vegetables, tofu, and black pepper.",
  },
  {
    id: "ss-3",
    name: "Creamy tomato soup",
    category: "steaming-soup",
    price: 180,
    approx_qty_gms: 250,
    description: "Rich tomato soup prepared with fresh cream and herbs",
  },
  {
    id: "ss-4",
    name: "Sweet corn soup",
    category: "steaming-soup",
    price: 150,
    approx_qty_gms: 250,
    description: "Delicate and creamy soup made from fresh corn kernels",
  },
  {
    id: "ss-5",
    name: "Manchurian Soup",
    category: "steaming-soup",
    price: 170,
    approx_qty_gms: 250,
    description: "Manchurian balls in a tangy and spicy soup base",
  },
  // Yummy Pizza
 {
    id: "pz-1",
    name: "Paneer Tikka Pizza",
    category: "yummy-pizza",
    price: 340,
    approx_qty_gms: 450,
    description: "Tandoori paneer tikka, bell peppers, onions, and rich mozzarella cheese on a freshly baked pizza crust.",
  },
  {
    id: "pz-2",
    name: "Garden Feast Pizza",
    category: "yummy-pizza",
    price: 320,
    approx_qty_gms: 430,
    description: "Loaded with mushrooms, black olives, sweet corn, onions, capsicum, and extra mozzarella cheese.",
  },
  {
    id: "pz-3",
    name: "Margherita Pizza",
    category: "yummy-pizza",
    price: 220,
    approx_qty_gms: 450,
    description: "Classic pizza topped with rich tomato sauce, fresh mozzarella cheese, and aromatic basil leaves.",
  },
  {
    id: "pz-4",
    name: "Double Cheese Pizza",
    category: "yummy-pizza",
    price: 290,
    approx_qty_gms: 300,
    description: "A cheese lover's delight topped with double mozzarella, cheddar cheese, and Italian herbs.",
  },
  {
    id: "pz-5",
    name: "Farmhouse Pizza",
    category: "yummy-pizza",
    price: 220,
    approx_qty_gms: 300,
    description: "Fresh onions, capsicum, tomatoes, mushrooms, sweet corn, and mozzarella cheese on a crispy crust.",
  },
  {
    id: "pz-6",
    name: "Cheesy Garlic Pizza",
    category: "yummy-pizza",
    price: 200,
    approx_qty_gms: 280,
    description: "Loaded with mozzarella cheese, roasted garlic, Italian herbs, butter, and a crispy golden crust.",
  },
  {
    id: "pz-7",
    name: "Corn Mushroom Pizza",
    category: "yummy-pizza",
    price: 220,
    approx_qty_gms: 300,
    description: "Sweet corn, fresh mushrooms, onions, mozzarella cheese, and herbs on a delicious baked crust.",
  },
  {
    id: "pz-8",
    name: "Veg Loaded Pizza",
    category: "yummy-pizza",
    price: 250,
    approx_qty_gms: 350,
    description: "Loaded with onions, capsicum, sweet corn, black olives, baby corn, paneer, and generous mozzarella cheese.",
  },
  
  // Bread & Burger
  {
    id: "bb-1",
    name: "Aloo Tikki Burger",
    category: "bread-burger",
    price: 130,
    approx_qty_gms: 220,
    description: "Crispy potato patty, spicy green chutney, house mayo, and fresh vegetables in a bun.",
  },
  {
    id: "bb-2",
    name: "Cheese Veg Burger",
    category: "bread-burger",
    price: 150,
    approx_qty_gms: 240,
    description: "Soft burger bun filled with a crispy veg patty, melted cheese, fresh lettuce, tomato, and creamy mayo.",
  },
  {
    id: "bb-3",
    name: "Paneer Tikka Burger",
    category: "bread-burger",
    price: 170,
    approx_qty_gms: 250,
    description: "Grilled paneer tikka, onion rings, mint chutney, and lettuce served in a toasted bun.",
  },
  {
    id: "bb-4",
    name: "Spicy Mexican Burger",
    category: "bread-burger",
    price: 180,
    approx_qty_gms: 255,
    description: "Crispy veg patty topped with jalapeños, salsa, cheese, and spicy chipotle mayo.",
  },
  {
    id: "bb-5",
    name: "Double Cheese Burger",
    category: "bread-burger",
    price: 190,
    approx_qty_gms: 270,
    description: "Double cheese slices layered over a crunchy veg patty with lettuce and signature sauce.",
  },
  {
    id: "bb-6",
    name: "Peri Peri Burger",
    category: "bread-burger",
    price: 175,
    approx_qty_gms: 245,
    description: "Peri peri flavored veg patty with onions, tomato, lettuce, and spicy mayo in a soft bun.",
  },
  {
    id: "bb-7",
    name: "Crunchy Veg Supreme Burger",
    category: "bread-burger",
    price: 185,
    approx_qty_gms: 260,
    description: "Extra crunchy vegetable patty with cheese, lettuce, onions, and tangy burger sauce.",
  },
  {
    id: "bb-8",
    name: "Cheese Garlic Bread",
    category: "bread-burger",
    price: 160,
    approx_qty_gms: 180,
    description: "Freshly baked baguette topped with garlic herb butter and melted gooey mozzarella.",
  },
  // Snacks
  {
    id: "sk-1",
    name: "Crispy Veg Samosa",
    category: "snacks",
    price: 80,
    approx_qty_gms: 150,
    description: "Flaky golden pastry filled with spiced potato and green peas, served with sweet tamarind chutney.",
  },
  {
    id: "sk-2",
    name: "Assorted Veg Pakora",
    category: "snacks",
    price: 150,
    approx_qty_gms: 250,
    description: "Crispy gram flour fritters of potato, onion, spinach leaves, and fresh cottage cheese.",
  },
  {
    id: "sk-3",
    name: "Paneer Pakoda",
    category: "snacks",
    price: 120,
    approx_qty_gms: 180,
    description: "Soft paneer cubes coated in a spiced gram flour batter and deep-fried until crispy, served with mint chutney.",
  },
  {
    id: "sk-4",
    name: "Masala French Fries",
    category: "snacks",
    price: 110,
    approx_qty_gms: 170,
    description: "Golden crispy fries tossed with spicy peri-peri seasoning and served with tomato ketchup and mayo.",
  },
  {
    id: "sk-5",
    name: "Veg Spring Rolls",
    category: "snacks",
    price: 140,
    approx_qty_gms: 200,
    description: "Crunchy spring rolls stuffed with fresh vegetables and noodles, served with sweet chili sauce.",
  },
  {
    id: "sk-6",
    name: "Cheese Corn Balls",
    category: "snacks",
    price: 150,
    approx_qty_gms: 190,
    description: "Crispy golden balls filled with sweet corn and melted cheese, served with spicy dip.",
  },
  {
    id: "sk-7",
    name: "Crispy Onion Rings",
    category: "snacks",
    price: 130,
    approx_qty_gms: 180,
    description: "Fresh onion rings coated in seasoned breadcrumbs and fried until golden, served with garlic mayo.",
  },
  // Sandwiches
  {
    id: "sd-1",
    name: "Bombay Grilled Sandwich",
    category: "sandwiches",
    price: 140,
    approx_qty_gms: 250,
    description: "Spicy potato mash, sliced cucumber, tomato, red onion, and mint chutney grilled in white bread.",
  },
  {
    id: "sd-2",
    name: "Paneer Club Sandwich",
    category: "sandwiches",
    price: 180,
    approx_qty_gms: 300,
    description: "Double decker sandwich layered with paneer tikka, cheese, crisp lettuce, and fresh tomatoes.",
  },
  {
    id: "sd-3",
    name: "Veg Cheese Sandwich",
    category: "sandwiches",
    price: 150,
    approx_qty_gms: 260,
    description: "Fresh vegetables layered with melted cheese, mint chutney, and butter, grilled until golden brown.",
  },
  {
    id: "sd-4",
    name: "Paneer Tikka Sandwich",
    category: "sandwiches",
    price: 180,
    approx_qty_gms: 280,
    description: "Grilled paneer tikka, onions, capsicum, and spicy mayo served between toasted bread slices.",
  },
  {
    id: "sd-5",
    name: "Corn Cheese Sandwich",
    category: "sandwiches",
    price: 160,
    approx_qty_gms: 270,
    description: "Sweet corn mixed with creamy cheese, herbs, and butter, grilled in crispy bread.",
  },
  {
    id: "sd-6",
    name: "Mexican Veg Sandwich",
    category: "sandwiches",
    price: 190,
    approx_qty_gms: 290,
    description: "Loaded with spicy Mexican vegetables, jalapeños, cheese, and chipotle sauce in toasted bread.",
  },
  {
    id: "sd-7",
    name: "Mushroom Cheese Sandwich",
    category: "sandwiches",
    price: 175,
    approx_qty_gms: 275,
    description: "Sautéed mushrooms, melted cheese, herbs, and creamy garlic mayo grilled in fresh bread.",
  },
  {
    id: "sd-8",
    name: "Club Veg Sandwich",
    category: "sandwiches",
    price: 200,
    approx_qty_gms: 320,
    description: "Triple-layer sandwich with fresh vegetables, cheese, lettuce, tomato, cucumber, and house dressing.",
  },
  // Baked Dish
  {
    id: "bd-1",
    name: "Lasagna Al Forno",
    category: "baked-dish",
    price: 280,
    approx_qty_gms: 350,
    description: "Layers of pasta sheets, mixed vegetables, marinara sauce, and creamy bechamel, baked to golden.",
  },
  {
    id: "bd-2",
    name: "Mac & Cheese Bake",
    category: "baked-dish",
    price: 240,
    approx_qty_gms: 300,
    description: "Elbow macaroni in a rich, creamy three-cheese sauce, baked with a crispy breadcrumb topping.",
  },
  {
    id: "bd-3",
    name: "Vegetable Lasagna",
    category: "baked-dish",
    price: 260,
    approx_qty_gms: 320,
    description: "Layers of pasta, fresh vegetables, rich tomato sauce, and mozzarella cheese baked until golden.",
  },
  {
    id: "bd-4",
    name: "Cheesy Baked Pasta",
    category: "baked-dish",
    price: 250,
    approx_qty_gms: 310,
    description: "Penne pasta tossed in creamy white sauce with vegetables, topped with mozzarella and baked to perfection.",
  },
  {
    id: "bd-5",
    name: "Stuffed Baked Bell Peppers",
    category: "baked-dish",
    price: 270,
    approx_qty_gms: 300,
    description: "Bell peppers stuffed with herbed rice, vegetables, and cheese, oven-baked until tender.",
  },
  {
    id: "bd-6",
    name: "Spinach & Cheese Casserole",
    category: "baked-dish",
    price: 280,
    approx_qty_gms: 330,
    description: "Fresh spinach blended with creamy cheese sauce and baked with a crispy golden cheese crust.",
  },
  {
    id: "bd-7",
    name: "Baked Veg Au Gratin",
    category: "baked-dish",
    price: 290,
    approx_qty_gms: 340,
    description: "Seasonal vegetables in a rich creamy sauce topped with cheese and breadcrumbs, baked until bubbly and golden.",
  },
  // Italian Pastas
  {
    id: "ip-1",
    name: "Penne Arrabiata",
    category: "italian-pastas",
    price: 260,
    approx_qty_gms: 320,
    description: "Penne pasta tossed in a spicy garlic and herb tomato sauce with fresh basil and olive oil.",
  },
  {
    id: "ip-2",
    name: "Creamy Alfredo Fettuccine",
    category: "italian-pastas",
    price: 290,
    approx_qty_gms: 340,
    description: "Rich white parmesan cream sauce tossed with fettuccine pasta, sliced mushrooms, and broccoli.",
  },
  {
    id: "ip-3",
    name: "Spaghetti Aglio Olio",
    category: "italian-pastas",
    price: 270,
    approx_qty_gms: 320,
    description: "Spaghetti tossed with extra virgin olive oil, minced garlic, chili flakes, and parsley.",
  },
  {
    id: "ip-4",
    name: "Creamy Basil Pesto Penne",
    category: "italian-pastas",
    price: 280,
    approx_qty_gms: 320,
    description: "Penne pasta tossed in a rich sauce made from fresh basil, garlic, pine nuts, and parmesan.",
  },
  {
    id: "ip-5",
    name: "Baked Macaroni & Cheese",
    category: "italian-pastas",
    price: 250,
    approx_qty_gms: 300,
    description: "Macaroni baked in a creamy cheddar and mozzarella cheese sauce with a breadcrumb crust.",
  },
  {
    id: "ip-6",
    name: "Mushroom & Spinach Ravioli",
    category: "italian-pastas",
    price: 320,
    approx_qty_gms: 300,
    description: "Handcrafted ravioli stuffed with wild mushrooms and spinach, served in white garlic sauce.",
  },
  {
    id: "ip-7",
    name: "Pink Sauce Penne Pasta",
    category: "italian-pastas",
    price: 270,
    approx_qty_gms: 330,
    description: "Penne tossed in a delicious blend of tomato marinara and creamy alfredo sauce.",
  },
  // Chinese Cuisine Starters
  {
    id: "cs-1",
    name: "Veg Spring Rolls",
    category: "chinese-cuisine-starters",
    price: 170,
    approx_qty_gms: 200,
    description: "Crispy rolls stuffed with seasoned stir-fried vegetables, served with sweet chili dip.",
  },
  {
    id: "cs-2",
    name: "Gobi Manchurian Dry",
    category: "chinese-cuisine-starters",
    price: 190,
    approx_qty_gms: 250,
    description: "Crispy cauliflower florets tossed with ginger, garlic, soy sauce, and spring onions.",
  },
  {
    id: "cs-3",
    name: "Veg Spring Rolls",
    category: "chinese-cuisine-starters",
    price: 180,
    approx_qty_gms: 220,
    description: "Crispy spring rolls stuffed with fresh vegetables and noodles, served with sweet chili sauce.",
  },
  {
    id: "cs-4",
    name: "Crispy Chilli Potato",
    category: "chinese-cuisine-starters",
    price: 200,
    approx_qty_gms: 240,
    description: "Golden potato fingers tossed in spicy garlic, soy sauce, sesame seeds, and spring onions.",
  },
  {
    id: "cs-5",
    name: "Paneer Chilli Dry",
    category: "chinese-cuisine-starters",
    price: 230,
    approx_qty_gms: 250,
    description: "Crispy paneer cubes stir-fried with onions, capsicum, garlic, green chilies, and Chinese sauces.",
  },
  {
    id: "cs-6",
    name: "Honey Chilli Potato",
    category: "chinese-cuisine-starters",
    price: 210,
    approx_qty_gms: 240,
    description: "Crunchy potato fries coated in a sweet and spicy honey chili glaze with sesame seeds.",
  },
  {
    id: "cs-7",
    name: "Dragon Paneer",
    category: "chinese-cuisine-starters",
    price: 240,
    approx_qty_gms: 260,
    description: "Crispy paneer strips tossed in fiery dragon sauce with garlic, chilies, and spring onions.",
  },
  {
    id: "cs-8",
    name: "Veg Manchurian Dry",
    category: "chinese-cuisine-starters",
    price: 220,
    approx_qty_gms: 250,
    description: "Vegetable dumplings stir-fried with garlic, ginger, soy sauce, and crunchy bell peppers.",
  },
  {
    id: "cs-9",
    name: "Crispy Corn Pepper Salt",
    category: "chinese-cuisine-starters",
    price: 190,
    approx_qty_gms: 220,
    description: "Golden fried sweet corn seasoned with salt, black pepper, garlic, and spring onions.",
  },
  // Chinese Cuisine Main Course
  {
    id: "cm-1",
    name: "Veg Hakka Noodles",
    category: "chinese-cuisine-main-course",
    price: 210,
    approx_qty_gms: 350,
    description: "Classic Chinese-style wok-tossed noodles with colorful julienne vegetables.",
  },
  {
    id: "cm-2",
    name: "Veg Fried Rice",
    category: "chinese-cuisine-main-course",
    price: 200,
    approx_qty_gms: 350,
    description: "Fluffy basmati rice stir-fried with diced garden vegetables and dark soy sauce.",
  },
  {
    id: "cm-3",
    name: "Schezwan Fried Rice",
    category: "chinese-cuisine-main-course",
    price: 230,
    approx_qty_gms: 360,
    description: "Spicy fried rice tossed with fresh vegetables, Schezwan sauce, garlic, and spring onions.",
  },
  {
    id: "cm-4",
    name: "Veg Triple Schezwan Rice",
    category: "chinese-cuisine-main-course",
    price: 280,
    approx_qty_gms: 450,
    description: "A combination of fried rice, Hakka noodles, and spicy Schezwan gravy topped with crispy noodles.",
  },
  {
    id: "cm-5",
    name: "Paneer Chilli Noodles",
    category: "chinese-cuisine-main-course",
    price: 260,
    approx_qty_gms: 380,
    description: "Wok-tossed Hakka noodles with crispy paneer, colorful vegetables, and spicy chili garlic sauce.",
  },
  {
    id: "cm-6",
    name: "Veg Manchurian with Fried Rice",
    category: "chinese-cuisine-main-course",
    price: 290,
    approx_qty_gms: 430,
    description: "Vegetable Manchurian balls served with flavorful vegetable fried rice and Manchurian gravy.",
  },
  {
    id: "cm-7",
    name: "Singapore Noodles",
    category: "chinese-cuisine-main-course",
    price: 250,
    approx_qty_gms: 360,
    description: "Thin rice noodles stir-fried with vegetables, curry spices, soy sauce, and sesame oil.",
  },
  {
    id: "cm-8",
    name: "Veg Chow Mein",
    category: "chinese-cuisine-main-course",
    price: 220,
    approx_qty_gms: 350,
    description: "Classic stir-fried noodles with cabbage, carrots, capsicum, bean sprouts, and savory Chinese sauces.",
  },
  // Sizzler
  {
    id: "sz-1",
    name: "Paneer Tikka Sizzler",
    category: "sizzler",
    price: 390,
    approx_qty_gms: 600,
    description: "Grilled paneer skewers served sizzling with buttered rice, roasted veggies, fries, and garlic sauce.",
  },
  {
    id: "sz-2",
    name: "Chinese Sizzler Combo",
    category: "sizzler",
    price: 370,
    approx_qty_gms: 580,
    description: "Sizzling combination of Hakka noodles, wet manchurian, crispy chili potato, and stir-fry.",
  },
  {
    id: "sz-3",
    name: "Veg Sizzler",
    category: "sizzler",
    price: 360,
    approx_qty_gms: 580,
    description: "A sizzling platter of grilled vegetables, buttered rice, crispy fries, and rich brown sauce.",
  },
  {
    id: "sz-4",
    name: "Mexican Sizzler",
    category: "sizzler",
    price: 410,
    approx_qty_gms: 620,
    description: "Mexican-style rice served with grilled vegetables, kidney beans, nachos, salsa, and cheese sauce on a hot plate.",
  },
  {
    id: "sz-5",
    name: "Mushroom Cheese Sizzler",
    category: "sizzler",
    price: 420,
    approx_qty_gms: 610,
    description: "Grilled mushrooms topped with melted cheese, served with herb rice, vegetables, fries, and creamy garlic sauce.",
  },
  {
    id: "sz-6",
    name: "Italian Pasta Sizzler",
    category: "sizzler",
    price: 430,
    approx_qty_gms: 630,
    description: "Creamy white sauce pasta served sizzling with grilled vegetables, garlic bread, fries, and cheese sauce.",
  },
  {
    id: "sz-7",
    name: "Peri Peri Paneer Sizzler",
    category: "sizzler",
    price: 440,
    approx_qty_gms: 620,
    description: "Peri peri marinated paneer served with seasoned rice, grilled vegetables, crispy fries, and spicy sauce.",
  },
  {
    id: "sz-8",
    name: "Chinese Sizzler",
    category: "sizzler",
    price: 450,
    approx_qty_gms: 650,
    description: "Schezwan fried rice, Hakka noodles, Manchurian balls, stir-fried vegetables, and spicy gravy served on a sizzling platter.",
  },
  {
    id: "sz-9",
    name: "Cheesy Cottage Cheese Sizzler",
    category: "sizzler",
    price: 460,
    approx_qty_gms: 640,
    description: "Grilled cottage cheese topped with cheese sauce, served with butter rice, vegetables, fries, and herb seasoning on a hot plate.",
  },
  // Paneer Ka Khazana
  {
    id: "pk-1",
    name: "Paneer Butter Masala",
    category: "paneer-ka-khazana",
    price: 280,
    approx_qty_gms: 400,
    description: "Soft cottage cheese cubes cooked in a sweet, rich, and creamy tomato and butter gravy.",
  },
  {
    id: "pk-2",
    name: "Kadai Paneer",
    category: "paneer-ka-khazana",
    price: 270,
    approx_qty_gms: 400,
    description: "Paneer chunks sauteed with thick capsicum and onion pieces in a spicy tomato gravy.",
  },
  {
    id: "pk-3",
    name: "Shahi Paneer Creamy",
    category: "paneer-ka-khazana",
    price: 290,
    approx_qty_gms: 400,
    description: "Soft paneer cubes cooked in a rich, sweet, and aromatic onion-cashew nut gravy.",
  },
  {
    id: "pk-4",
    name: "Palak Paneer Lahsuni",
    category: "paneer-ka-khazana",
    price: 260,
    approx_qty_gms: 400,
    description: "Fresh cottage cheese cubes cooked in a spiced spinach puree with tempered garlic.",
  },
  {
    id: "pk-5",
    name: "Spicy Paneer Bhurji",
    category: "paneer-ka-khazana",
    price: 310,
    approx_qty_gms: 350,
    description: "Scrambled cottage cheese stir-fried with onions, tomatoes, green chilies, and coriander.",
  },
  {
    id: "pk-6",
    name: "Paneer Tikka Masala Dry",
    category: "paneer-ka-khazana",
    price: 300,
    approx_qty_gms: 400,
    description: "Marinated grilled paneer chunks cooked in a thick spicy onion-tomato gravy.",
  },
  {
    id: "pk-7",
    name: "Mutter Paneer Home Style",
    category: "paneer-ka-khazana",
    price: 250,
    approx_qty_gms: 400,
    description: "A delicious combination of green peas and paneer cubes cooked in a rich onion-tomato sauce.",
  },
  // Kofta Ka Kamal
  {
    id: "kk-1",
    name: "Malai Kofta",
    category: "kofta-ka-kamal",
    price: 290,
    approx_qty_gms: 400,
    description: "Deep-fried paneer and potato dumplings filled with raisins, served in mild cashew cream gravy.",
  },
  {
    id: "kk-2",
    name: "Shaam Saavera Kofta",
    category: "kofta-ka-kamal",
    price: 310,
    approx_qty_gms: 400,
    description: "Spinach-wrapped paneer dumplings fried and simmered in a tangy tomato-butter gravy.",
  },
  {
    id: "kk-3",
    name: "Malai Kofta",
    category: "kofta-ka-kamal",
    price: 320,
    approx_qty_gms: 400,
    description: "Soft paneer and potato dumplings simmered in a rich, creamy tomato-cashew gravy with aromatic spices.",
  },
  {
    id: "kk-4",
    name: "Veg Nargisi Kofta",
    category: "kofta-ka-kamal",
    price: 330,
    approx_qty_gms: 420,
    description: "Mixed vegetable koftas stuffed with paneer, served in a flavorful onion and tomato-based curry.",
  },
  {
    id: "kk-5",
    name: "Paneer Kofta Curry",
    category: "kofta-ka-kamal",
    price: 340,
    approx_qty_gms: 410,
    description: "Delicate paneer koftas cooked in a creamy makhani gravy infused with butter and fresh cream.",
  },
  {
    id: "kk-6",
    name: "Hara Bhara Kofta",
    category: "kofta-ka-kamal",
    price: 325,
    approx_qty_gms: 400,
    description: "Spinach and green pea koftas served in a mildly spiced cashew and cream-based curry.",
  },
  {
    id: "kk-7",
    name: "Cheese Stuffed Kofta",
    category: "kofta-ka-kamal",
    price: 350,
    approx_qty_gms: 430,
    description: "Golden-fried vegetable koftas stuffed with molten cheese, served in a rich tomato gravy.",
  },
  {
    id: "kk-8",
    name: "Methi Malai Kofta",
    category: "kofta-ka-kamal",
    price: 345,
    approx_qty_gms: 420,
    description: "Fenugreek-flavored koftas simmered in a creamy white gravy with cashews and fresh cream.",
  },
  {
    id: "kk-9",
    name: "Navratan Kofta",
    category: "kofta-ka-kamal",
    price: 360,
    approx_qty_gms: 430,
    description: "Royal vegetable and dry fruit koftas cooked in a luxurious saffron-infused cashew gravy.",
  },
  // Cheese Ka Khazana
  {
    id: "ck-1",
    name: "Cheese Butter Masala",
    category: "cheese-ka-khazana",
    price: 320,
    approx_qty_gms: 400,
    description: "Grated and diced cheese cubes cooked in a rich, buttery, spiced onion-tomato gravy.",
  },
  {
    id: "ck-2",
    name: "Cheese Angara",
    category: "cheese-ka-khazana",
    price: 340,
    approx_qty_gms: 400,
    description: "Spicy and smokey gravy topped with charcoal aroma and a generous layer of processed cheese.",
  },
  {
    id: "ck-3",
    name: "Cheese Angara",
    category: "cheese-ka-khazana",
    price: 340,
    approx_qty_gms: 410,
    description: "Soft cheese cubes cooked in a smoky tomato-onion gravy with aromatic spices and charcoal flavor.",
  },
  {
    id: "ck-4",
    name: "Cheese Tikka Masala",
    category: "cheese-ka-khazana",
    price: 350,
    approx_qty_gms: 420,
    description: "Grilled cheese cubes simmered in a creamy tomato-based tikka masala gravy with fresh cream.",
  },
  {
    id: "ck-5",
    name: "Cheese Lababdar",
    category: "cheese-ka-khazana",
    price: 360,
    approx_qty_gms: 420,
    description: "Rich and creamy cheese curry prepared with buttery tomato gravy, cashew paste, and Indian spices.",
  },
  {
    id: "ck-6",
    name: "Cheese Kadai",
    category: "cheese-ka-khazana",
    price: 345,
    approx_qty_gms: 410,
    description: "Cheese cubes cooked with capsicum, onions, tomatoes, and freshly ground kadai masala.",
  },
  {
    id: "ck-7",
    name: "Cheese Do Pyaza",
    category: "cheese-ka-khazana",
    price: 355,
    approx_qty_gms: 400,
    description: "Tender cheese cubes cooked with caramelized onions, tomato gravy, and fragrant Indian spices.",
  },
  {
    id: "ck-8",
    name: "Cheese Kolhapuri",
    category: "cheese-ka-khazana",
    price: 370,
    approx_qty_gms: 420,
    description: "Spicy cheese curry prepared in authentic Kolhapuri masala with coconut, red chilies, and herbs.",
  },
  // Indian Main Course
  {
    id: "im-1",
    name: "Veg Kolhapuri",
    category: "indian-main-course",
    price: 240,
    approx_qty_gms: 400,
    description: "Spicy mixed vegetables cooked in Kolhapuri style with shredded coconut and dry red chilies.",
  },
  {
    id: "im-2",
    name: "Aloo Gobhi Adraki",
    category: "indian-main-course",
    price: 210,
    approx_qty_gms: 380,
    description: "Dry home-style dish of fresh cauliflower and potatoes cooked with cumin and julienned ginger.",
  },
  {
    id: "im-3",
    name: "Veg Jaipuri",
    category: "indian-main-course",
    price: 250,
    approx_qty_gms: 400,
    description: "A royal Rajasthani-style curry with mixed vegetables, paneer, and rich tomato-cashew gravy.",
  },
  {
    id: "im-4",
    name: "Veg Handi",
    category: "indian-main-course",
    price: 260,
    approx_qty_gms: 410,
    description: "Seasonal vegetables cooked in a traditional handi with aromatic Indian spices and creamy gravy.",
  },
  {
    id: "im-5",
    name: "Mix Veg Curry",
    category: "indian-main-course",
    price: 230,
    approx_qty_gms: 400,
    description: "Fresh mixed vegetables simmered in a flavorful onion-tomato gravy with traditional Indian spices.",
  },
  {
    id: "im-6",
    name: "Veg Hyderabadi",
    category: "indian-main-course",
    price: 270,
    approx_qty_gms: 420,
    description: "Mixed vegetables cooked in a rich Hyderabadi-style gravy with cashews, coconut, and aromatic spices.",
  },
  {
    id: "im-7",
    name: "Veg Kadai",
    category: "indian-main-course",
    price: 255,
    approx_qty_gms: 410,
    description: "Fresh vegetables stir-cooked with onions, capsicum, tomatoes, and freshly ground kadai masala.",
  },
  {
    id: "im-8",
    name: "Veg Makhanwala",
    category: "indian-main-course",
    price: 280,
    approx_qty_gms: 420,
    description: "Mixed vegetables cooked in a buttery tomato gravy enriched with fresh cream and aromatic spices.",
  },
  {
    id: "im-9",
    name: "Navratan Korma",
    category: "indian-main-course",
    price: 290,
    approx_qty_gms: 420,
    description: "A rich Mughlai curry with vegetables, paneer, fruits, nuts, and creamy cashew gravy.",
  },
  {
    id: "im-10",
    name: "Veg Jalfrezi",
    category: "indian-main-course",
    price: 260,
    approx_qty_gms: 400,
    description: "Crunchy vegetables stir-fried in a tangy tomato-onion masala with colorful bell peppers.",
  },
  {
    id: "im-11",
    name: "Dum Aloo Kashmiri",
    category: "indian-main-course",
    price: 275,
    approx_qty_gms: 390,
    description: "Baby potatoes slow-cooked in a mildly spiced Kashmiri yogurt and tomato-based gravy.",
  },
  {
    id: "im-12",
    name: "Methi Mutter Malai",
    category: "indian-main-course",
    price: 285,
    approx_qty_gms: 400,
    description: "Fresh fenugreek leaves and green peas cooked in a rich, creamy, mildly sweet white gravy.",
  },
  // Indian Bread
  {
    id: "ib-1",
    name: "Butter Naan",
    category: "indian-bread",
    price: 50,
    approx_qty_gms: 100,
    description: "Soft and pillowy flatbread baked in tandoor oven, brushed with pure butter.",
  },
  {
    id: "ib-2",
    name: "Garlic Naan",
    category: "indian-bread",
    price: 65,
    approx_qty_gms: 110,
    description: "Flatbread infused with fresh minced garlic and coriander leaves before baking.",
  },
  {
    id: "ib-3",
    name: "Cheese Naan",
    category: "indian-bread",
    price: 110,
    approx_qty_gms: 140,
    description: "Tandoor-baked naan stuffed with melted cheese and brushed with butter.",
  },
  {
    id: "ib-4",
    name: "Lachha Paratha",
    category: "indian-bread",
    price: 80,
    approx_qty_gms: 120,
    description: "Multi-layered whole wheat paratha cooked with ghee until crispy and flaky.",
  },
  {
    id: "ib-5",
    name: "Stuffed Kulcha",
    category: "indian-bread",
    price: 90,
    approx_qty_gms: 140,
    description: "Soft kulcha stuffed with spiced potato filling and baked in a traditional tandoor.",
  },
  {
    id: "ib-6",
    name: "Missi Roti",
    category: "indian-bread",
    price: 60,
    approx_qty_gms: 100,
    description: "Traditional Punjabi flatbread made with gram flour, whole wheat flour, and spices.",
  },
  {
    id: "ib-7",
    name: "Tandoori Roti",
    category: "indian-bread",
    price: 40,
    approx_qty_gms: 90,
    description: "Classic whole wheat flatbread baked in a clay tandoor with a smoky flavor.",
  },
  {
    id: "ib-8",
    name: "Plain Kulcha",
    category: "indian-bread",
    price: 60,
    approx_qty_gms: 100,
    description: "Soft and fluffy refined flour bread baked in a tandoor and lightly buttered.",
  },
  {
    id: "ib-9",
    name: "Hariyali Naan",
    category: "indian-bread",
    price: 90,
    approx_qty_gms: 120,
    description: "Fresh herb naan flavored with coriander, mint, garlic, and butter.",
  },
  {
    id: "ib-10",
    name: "Cheese Garlic Naan",
    category: "indian-bread",
    price: 130,
    approx_qty_gms: 150,
    description: "Cheese-filled naan topped with roasted garlic, butter, and fresh coriander.",
  },
  // Dal Ke Diwane
  {
    id: "dd-1",
    name: "Dal Makhani",
    category: "dal-ke-diwane",
    price: 220,
    approx_qty_gms: 400,
    description: "Traditional slow-cooked black lentils simmered overnight with tomatoes, butter, and cream.",
  },
  {
    id: "dd-2",
    name: "Dal Tadka Double",
    category: "dal-ke-diwane",
    price: 180,
    approx_qty_gms: 380,
    description: "Yellow pigeon pea lentils tempered with cumin, garlic, red chilies, and pure ghee.",
  },
  {
    id: "dd-3",
    name: "Dal Tadka",
    category: "dal-ke-diwane",
    price: 190,
    approx_qty_gms: 400,
    description: "Yellow lentils tempered with cumin, garlic, onions, tomatoes, and aromatic Indian spices.",
  },
  {
    id: "dd-4",
    name: "Dal Fry",
    category: "dal-ke-diwane",
    price: 200,
    approx_qty_gms: 400,
    description: "Cooked toor dal sautéed with onions, tomatoes, garlic, and traditional Indian tempering.",
  },
  {
    id: "dd-5",
    name: "Gujarati Dal",
    category: "dal-ke-diwane",
    price: 180,
    approx_qty_gms: 420,
    description: "Sweet and tangy Gujarati-style dal prepared with jaggery, tamarind, peanuts, and spices.",
  },
  {
    id: "dd-6",
    name: "Panchmel Dal",
    category: "dal-ke-diwane",
    price: 230,
    approx_qty_gms: 410,
    description: "A nutritious blend of five lentils slow-cooked with ghee, garlic, and aromatic spices.",
  },
  {
    id: "dd-7",
    name: "Dal Palak",
    category: "dal-ke-diwane",
    price: 210,
    approx_qty_gms: 410,
    description: "Fresh spinach cooked with yellow lentils, garlic, cumin, and mild Indian spices.",
  },
  {
    id: "dd-8",
    name: "Lasooni Dal",
    category: "dal-ke-diwane",
    price: 220,
    approx_qty_gms: 400,
    description: "Flavorful yellow lentils topped with a smoky garlic tempering and fresh coriander.",
  },
  {
    id: "dd-9",
    name: "Dal Maharani",
    category: "dal-ke-diwane",
    price: 250,
    approx_qty_gms: 420,
    description: "Rich and creamy black lentils slow-cooked with butter, cream, and aromatic spices.",
  },
  {
    id: "dd-10",
    name: "Mixed Dal Curry",
    category: "dal-ke-diwane",
    price: 210,
    approx_qty_gms: 410,
    description: "A hearty combination of assorted lentils cooked with onions, tomatoes, and traditional Indian spices.",
  },
  // Basmati Ka Khazana
  {
    id: "bk-1",
    name: "Hyderabadi Veg Biryani",
    category: "basmati-ka-khazana",
    price: 280,
    approx_qty_gms: 500,
    description: "Aromatic basmati rice cooked on slow dum with fresh herbs, spices, and veggies, served with raita.",
  },
  {
    id: "bk-2",
    name: "Jeera Rice",
    category: "basmati-ka-khazana",
    price: 140,
    approx_qty_gms: 350,
    description: "Long-grain basmati rice tempered with ghee and aromatic cumin seeds.",
  },
  {
    id: "bk-3",
    name: "Veg Dum Biryani",
    category: "basmati-ka-khazana",
    price: 290,
    approx_qty_gms: 500,
    description: "Fragrant basmati rice layered with mixed vegetables, saffron, herbs, and slow-cooked on dum, served with raita.",
  },
  {
    id: "bk-4",
    name: "Paneer Biryani",
    category: "basmati-ka-khazana",
    price: 320,
    approx_qty_gms: 520,
    description: "Long-grain basmati rice cooked with marinated paneer cubes, aromatic spices, and fresh mint.",
  },
  {
    id: "bk-5",
    name: "Kashmiri Pulao",
    category: "basmati-ka-khazana",
    price: 300,
    approx_qty_gms: 480,
    description: "Premium basmati rice cooked with dry fruits, fresh fruits, saffron, and mild aromatic spices.",
  },
  {
    id: "bk-6",
    name: "Veg Pulao",
    category: "basmati-ka-khazana",
    price: 230,
    approx_qty_gms: 450,
    description: "Flavorful basmati rice cooked with fresh vegetables, whole spices, and herbs.",
  },
  {
    id: "bk-7",
    name: "Schezwan Fried Rice",
    category: "basmati-ka-khazana",
    price: 250,
    approx_qty_gms: 450,
    description: "Spicy basmati fried rice tossed with vegetables, garlic, Schezwan sauce, and spring onions.",
  },
  {
    id: "bk-8",
    name: "Peas Pulao",
    category: "basmati-ka-khazana",
    price: 210,
    approx_qty_gms: 400,
    description: "Aromatic basmati rice cooked with fresh green peas, whole spices, butter, and herbs.",
  },
  // Kaju Ki Peshkash
  {
    id: "kp-1",
    name: "Kaju Curry Spicy",
    category: "kaju-ki-peshkash",
    price: 320,
    approx_qty_gms: 400,
    description: "Roasted cashew nuts cooked in a rich, velvety onion-tomato and cashew gravy.",
  },
  {
    id: "kp-2",
    name: "Kaju Khoya Paneer",
    category: "kaju-ki-peshkash",
    price: 340,
    approx_qty_gms: 400,
    description: "Rich, mildly sweet curry made with cashews, khoya (evaporated milk solids), and paneer cubes.",
  },
  {
    id: "kp-3",
    name: "Kaju Masala",
    category: "kaju-ki-peshkash",
    price: 330,
    approx_qty_gms: 400,
    description: "Roasted cashew nuts cooked in a rich onion-tomato masala with aromatic Indian spices.",
  },
  {
    id: "kp-4",
    name: "Kaju Butter Masala",
    category: "kaju-ki-peshkash",
    price: 350,
    approx_qty_gms: 420,
    description: "Crunchy cashew nuts simmered in a creamy buttery tomato gravy enriched with fresh cream.",
  },
  {
    id: "kp-5",
    name: "Kaju Makhani",
    category: "kaju-ki-peshkash",
    price: 360,
    approx_qty_gms: 420,
    description: "Premium cashew nuts cooked in a velvety makhani gravy with butter, cream, and mild spices.",
  },
  {
    id: "kp-6",
    name: "Kaju Paneer Curry",
    category: "kaju-ki-peshkash",
    price: 380,
    approx_qty_gms: 430,
    description: "Soft paneer cubes and roasted cashews cooked together in a rich tomato-cashew gravy.",
  },
  {
    id: "kp-7",
    name: "Kaju Korma",
    category: "kaju-ki-peshkash",
    price: 390,
    approx_qty_gms: 430,
    description: "Whole cashew nuts simmered in a luxurious Mughlai-style white gravy with cream and aromatic spices.",
  },
  // Special Soya Chaap
  {
    id: "sc-1",
    name: "Soya Chaap Masala",
    category: "special-soya-chaap",
    price: 240,
    approx_qty_gms: 400,
    description: "Succulent pieces of soy chaap cooked in a semi-dry onion, tomato, and bell pepper masala.",
  },
  {
    id: "sc-2",
    name: "Tandoori Malai Chaap",
    category: "special-soya-chaap",
    price: 260,
    approx_qty_gms: 350,
    description: "Soy chaap marinated in yogurt, cashew cream, and cardamom, char-grilled in tandoor.",
  },
  {
    id: "sc-3",
    name: "Afghani Soya Chaap",
    category: "special-soya-chaap",
    price: 270,
    approx_qty_gms: 420,
    description: "Tender soy chaap cooked in a creamy Afghani-style gravy with fresh cream, butter, and mild spices.",
  },
  {
    id: "sc-4",
    name: "Malai Soya Chaap",
    category: "special-soya-chaap",
    price: 280,
    approx_qty_gms: 420,
    description: "Soft soy chaap simmered in a rich, creamy white gravy flavored with cashews and aromatic herbs.",
  },
  {
    id: "sc-5",
    name: "Soya Chaap Butter Masala",
    category: "special-soya-chaap",
    price: 290,
    approx_qty_gms: 430,
    description: "Juicy soy chaap cooked in a buttery tomato gravy with fresh cream and flavorful Indian spices.",
  },
  {
    id: "sc-6",
    name: "Kadai Soya Chaap",
    category: "special-soya-chaap",
    price: 275,
    approx_qty_gms: 420,
    description: "Soya chaap tossed with onions, capsicum, tomatoes, and freshly ground kadai masala.",
  },
  {
    id: "sc-7",
    name: "Achari Soya Chaap",
    category: "special-soya-chaap",
    price: 285,
    approx_qty_gms: 420,
    description: "Flavorful soy chaap cooked with tangy pickle spices, onions, tomatoes, and fresh herbs.",
  },
  {
    id: "sc-8",
    name: "Tandoori Soya Chaap Masala",
    category: "special-soya-chaap",
    price: 300,
    approx_qty_gms: 430,
    description: "Tandoori-marinated soy chaap cooked in a smoky tomato-onion gravy with butter and aromatic spices.",
  },
  // Tandoor Ke Sholay
  {
    id: "ts-1",
    name: "Paneer Tikka Lal Surkh",
    category: "tandoor-ke-sholay",
    price: 250,
    approx_qty_gms: 300,
    description: "Fresh cottage cheese chunks marinated in red chili paste and yogurt, skewered and baked.",
  },
  {
    id: "ts-2",
    name: "Tandoori Mushroom Tikka",
    category: "tandoor-ke-sholay",
    price: 230,
    approx_qty_gms: 250,
    description: "Fresh button mushrooms coated in spicy tandoori marinade, roasted over charcoal grill.",
  },
  {
    id: "ts-3",
    name: "Hariyali Paneer Tikka",
    category: "tandoor-ke-sholay",
    price: 260,
    approx_qty_gms: 300,
    description: "Paneer cubes marinated with mint, coriander, yogurt, and aromatic spices, grilled in a tandoor.",
  },
  {
    id: "ts-4",
    name: "Malai Paneer Tikka",
    category: "tandoor-ke-sholay",
    price: 280,
    approx_qty_gms: 320,
    description: "Soft paneer marinated in cream, cheese, yogurt, and mild spices, roasted until perfectly charred.",
  },
  {
    id: "ts-5",
    name: "Achari Paneer Tikka",
    category: "tandoor-ke-sholay",
    price: 270,
    approx_qty_gms: 310,
    description: "Paneer cubes marinated with tangy Indian pickle spices and yogurt, grilled in a traditional tandoor.",
  },
  {
    id: "ts-6",
    name: "Tandoori Mushroom",
    category: "tandoor-ke-sholay",
    price: 240,
    approx_qty_gms: 280,
    description: "Fresh mushrooms marinated in spicy yogurt, herbs, and tandoori masala, roasted to perfection.",
  },
  {
    id: "ts-7",
    name: "Veg Tandoori Platter",
    category: "tandoor-ke-sholay",
    price: 390,
    approx_qty_gms: 500,
    description: "A delicious assortment of paneer tikka, mushrooms, baby corn, and vegetables cooked in a clay tandoor.",
  },
  // Choice of Lassi
  {
    id: "ls-1",
    name: "Sweet Punjabi Lassi",
    category: "choice-of-lassi",
    price: 90,
    approx_qty_gms: 300,
    description: "Thick churned fresh yogurt drink sweetened with sugar and flavored with cardamom seeds.",
  },
  {
    id: "ls-2",
    name: "Mango Lassi Splash",
    category: "choice-of-lassi",
    price: 110,
    approx_qty_gms: 300,
    description: "Traditional yogurt smoothie blended with ripe mango pulp and topped with chopped nuts.",
  },
  {
  id: "ls-3",
  name: "Dry Fruit Lassi",
  category: "choice-of-lassi",
  price: 140,
  approx_qty_gms: 320,
  description: "Rich and creamy yogurt blended with almonds, cashews, pistachios, raisins, and flavored with cardamom for a refreshing drink.",
},
  {
    id: "ls-4",
    name: "Rose Lassi",
    category: "choice-of-lassi",
    price: 110,
    approx_qty_gms: 300,
    description: "Refreshing chilled yogurt drink flavored with rose syrup, sugar, and topped with dry rose petals.",
  },
  {
    id: "ls-5",
    name: "Kesar Pista Lassi",
    category: "choice-of-lassi",
    price: 140,
    approx_qty_gms: 320,
    description: "Rich and creamy lassi infused with saffron, chopped pistachios, and a touch of cardamom.",
  },
  // Dahi Ka Swad
  {
    id: "ds-1",
    name: "Dahi Bhalla Mitha",
    category: "dahi-ka-swad",
    price: 120,
    approx_qty_gms: 250,
    description: "Soft urad dal dumplings soaked in sweet yogurt, garnished with tamarind chutney and cumin.",
  },
  {
    id: "ds-2",
    name: "Veg Raita Boondi",
    category: "dahi-ka-swad",
    price: 80,
    approx_qty_gms: 200,
    description: "Chilled whisked curd mixed with crispy gram flour boondi beads and spice powder.",
  },
  {
    id: "ds-3",
    name: "Dahi Papdi Chaat",
    category: "dahi-ka-swad",
    price: 140,
    approx_qty_gms: 280,
    description: "Crispy papdi topped with chilled yogurt, potatoes, chutneys, sev, and fresh coriander.",
  },
  {
    id: "ds-4",
    name: "Boondi Raita",
    category: "dahi-ka-swad",
    price: 110,
    approx_qty_gms: 250,
    description: "Creamy yogurt mixed with crispy boondi, roasted cumin powder, black salt, and fresh coriander.",
  },
  {
    id: "ds-5",
    name: "Mixed Veg Raita",
    category: "dahi-ka-swad",
    price: 120,
    approx_qty_gms: 260,
    description: "Fresh yogurt blended with finely chopped cucumber, tomatoes, onions, carrots, and mild spices.",
  },
  {
    id: "ds-6",
    name: "Pineapple Raita",
    category: "dahi-ka-swad",
    price: 140,
    approx_qty_gms: 260,
    description: "Sweet and refreshing yogurt mixed with juicy pineapple pieces, roasted cumin, and fresh mint.",
  },
  // Papads
  {
    id: "pp-1",
    name: "Masala Papad Crispy",
    category: "papads",
    price: 50,
    approx_qty_gms: 50,
    description: "Crispy roasted papad topped with finely chopped onion, tomato, coriander, and chat masala.",
  },
  {
    id: "pp-2",
    name: "Roasted Papad (2 Pcs)",
    category: "papads",
    price: 25,
    approx_qty_gms: 20,
    description: "Traditional sun-dried lentil flatbread dry roasted over open flames.",
  },
  {
    id: "pp-3",
    name: "Fried Masala Papad",
    category: "papads",
    price: 60,
    approx_qty_gms: 55,
    description: "Crispy fried papad topped with chopped onions, tomatoes, coriander, lemon juice, and chaat masala.",
  },
  {
    id: "pp-4",
    name: "Cheese Masala Papad",
    category: "papads",
    price: 90,
    approx_qty_gms: 80,
    description: "Crunchy fried papad topped with grated cheese, onions, tomatoes, coriander, and flavorful spices.",
  },
  {
    id: "pp-5",
    name: "Corn Cheese Papad",
    category: "papads",
    price: 100,
    approx_qty_gms: 90,
    description: "Crispy fried papad loaded with sweet corn, grated cheese, fresh vegetables, and tangy seasoning.",
  },
  // Appetizer Salad
  {
    id: "as-1",
    name: "Garden Green Salad",
    category: "appetizer-salad",
    price: 70,
    approx_qty_gms: 150,
    description: "Fresh farm-fresh cucumber, onion, tomato, carrot slices, and green chillies served with lemon.",
  },
  {
    id: "as-2",
    name: "Spicy Kachumber Salad",
    category: "appetizer-salad",
    price: 80,
    approx_qty_gms: 180,
    description: "Finely diced cucumbers, onions, and tomatoes tossed with coriander, lemon juice, and chaat masala.",
  },
  {
    id: "as-3",
    name: "Greek Veg Salad",
    category: "appetizer-salad",
    price: 180,
    approx_qty_gms: 220,
    description: "Fresh lettuce, cucumber, tomatoes, olives, onions, and feta cheese tossed with olive oil and herbs.",
  },
  {
    id: "as-4",
    name: "Sprouts Salad",
    category: "appetizer-salad",
    price: 120,
    approx_qty_gms: 200,
    description: "Healthy mixed sprouts combined with onions, tomatoes, cucumber, lemon juice, and chaat masala.",
  },
  {
    id: "as-5",
    name: "Corn & Cucumber Salad",
    category: "appetizer-salad",
    price: 130,
    approx_qty_gms: 200,
    description: "Sweet corn, cucumber, onions, tomatoes, and fresh coriander tossed with lemon dressing.",
  },
  {
    id: "as-6",
    name: "Russian Salad",
    category: "appetizer-salad",
    price: 170,
    approx_qty_gms: 220,
    description: "Mixed vegetables and pineapple folded in creamy mayonnaise, garnished with fresh herbs.",
  },
  {
    id: "as-7",
    name: "Fruit & Veg Salad",
    category: "appetizer-salad",
    price: 160,
    approx_qty_gms: 230,
    description: "A refreshing combination of seasonal fruits, fresh vegetables, lettuce, and honey lemon dressing.",
  },
  // Smoothie
  {
    id: "sm-1",
    name: "Berry Blast Smoothie",
    category: "smoothie",
    price: 190,
    approx_qty_gms: 300,
    description: "Creamy banana and mixed forest berries blended with yogurt and organic honey.",
  },
  {
    id: "sm-2",
    name: "Green Apple Detox",
    category: "smoothie",
    price: 200,
    approx_qty_gms: 300,
    description: "Nutritious blend of crisp green apple, baby spinach, fresh cucumber, and chia seeds.",
  },
  {
    id: "sm-3",
    name: "Mango Delight Smoothie",
    category: "smoothie",
    price: 180,
    approx_qty_gms: 300,
    description: "Creamy ripe mango blended with chilled yogurt, milk, and a touch of honey for a tropical delight.",
  },
  {
    id: "sm-4",
    name: "Chocolate Banana Smoothie",
    category: "smoothie",
    price: 200,
    approx_qty_gms: 320,
    description: "Fresh banana blended with rich chocolate, milk, and yogurt for a thick and creamy treat.",
  },
  {
    id: "sm-5",
    name: "Strawberry Yogurt Smoothie",
    category: "smoothie",
    price: 210,
    approx_qty_gms: 300,
    description: "Sweet strawberries blended with creamy yogurt, fresh milk, and honey for a refreshing drink.",
  },
  // Chef Special Shake
  {
    id: "sh-1",
    name: "Premium Oreo Cookie Shake",
    category: "chef-special-shake",
    price: 180,
    approx_qty_gms: 350,
    description: "Blended milk, cookies, vanilla ice cream, and chocolate fudge topped with fresh whipped cream.",
  },
  {
    id: "sh-2",
    name: "Nutella Hazelnut Shake",
    category: "chef-special-shake",
    price: 220,
    approx_qty_gms: 350,
    description: "Indulgent shake blended with imported Nutella and toasted hazelnuts, finished with dark flakes.",
  },
 {
    id: "sh-3",
    name: "KitKat Chocolate Shake",
    category: "chef-special-shake",
    price: 210,
    approx_qty_gms: 350,
    description: "Creamy milkshake blended with KitKat chocolate, vanilla ice cream, and topped with whipped cream and chocolate drizzle.",
  },
  {
    id: "sh-4",
    name: "Ferrero Rocher Shake",
    category: "chef-special-shake",
    price: 260,
    approx_qty_gms: 360,
    description: "Rich Ferrero Rocher chocolates blended with milk, hazelnut spread, ice cream, and finished with whipped cream.",
  },
  {
    id: "sh-5",
    name: "Butterscotch Crunch Shake",
    category: "chef-special-shake",
    price: 200,
    approx_qty_gms: 350,
    description: "Smooth butterscotch milkshake blended with vanilla ice cream, caramel syrup, and crunchy butterscotch chips.",
  },
  {
    id: "sh-6",
    name: "Dry Fruit Royal Shake",
    category: "chef-special-shake",
    price: 240,
    approx_qty_gms: 360,
    description: "A rich blend of milk, almonds, cashews, pistachios, dates, and vanilla ice cream, topped with chopped dry fruits.",
  },
  // Shots
  {
    id: "st-1",
    name: "Ginger Lemon Mint Shot",
    category: "shots",
    price: 90,
    approx_qty_gms: 100,
    description: "A cold-pressed palate cleanser shot loaded with organic ginger root, lime, and mint.",
  },
  {
    id: "st-2",
    name: "Black Grapes",
    category: "shots",
    price: 110,
    approx_qty_gms: 200,
    description: "Fresh, juicy black grapes with a naturally sweet flavor and a refreshing burst of fruity goodness.",
  },
  {
    id: "st-3",
    name: "Litchi",
    category: "shots",
    price: 140,
    approx_qty_gms: 200,
    description: "Sweet, juicy lychees with a delicate floral aroma and a soft, refreshing texture.",
  },
  {
    id: "st-4",
    name: "Dragon Fruit",
    category: "shots",
    price: 180,
    approx_qty_gms: 220,
    description: "Fresh dragon fruit with mildly sweet white flesh, tiny crunchy seeds, and a refreshing tropical taste.",
  },
  {
    id: "st-5",
    name: "Kiwi",
    category: "shots",
    price: 170,
    approx_qty_gms: 200,
    description: "Fresh kiwi slices offering a perfect balance of sweet and tangy flavor, rich in vitamin C and antioxidants.",
  },
  // Desserts
  {
    id: "ic-1",
    name: "Vanilla Ice Cream",
    category: "desserts",
    price: 90,
    approx_qty_gms: 120,
    description: "Classic creamy vanilla ice cream made with rich milk and natural vanilla flavor.",
  },
  {
    id: "ic-2",
    name: "Chocolate Ice Cream",
    category: "desserts",
    price: 100,
    approx_qty_gms: 120,
    description: "Rich and creamy chocolate ice cream made with premium cocoa for a smooth and indulgent taste.",
  },
  {
    id: "ic-3",
    name: "Butterscotch Ice Cream",
    category: "desserts",
    price: 110,
    approx_qty_gms: 120,
    description: "Smooth butterscotch ice cream loaded with crunchy caramel chips and buttery sweetness.",
  },
  {
    id: "ic-4",
    name: "Sizzling Brownie with Vanilla Ice Cream",
    category: "desserts",
    price: 240,
    approx_qty_gms: 280,
    description: "Warm chocolate brownie served on a sizzling platter with creamy vanilla ice cream and hot chocolate sauce.",
  },
  {
    id: "ic-5",
    name: "Sizzling Brownie with Butterscotch Ice Cream",
    category: "desserts",
    price: 250,
    approx_qty_gms: 290,
    description: "Fresh chocolate brownie topped with butterscotch ice cream, sizzling caramel sauce, and crunchy nuts.",
  },
  {
    id: "ic-6",
    name: "Sizzling Nutty Delight Ice Cream",
    category: "desserts",
    price: 290,
    approx_qty_gms: 320,
    description: "A sizzling dessert featuring vanilla ice cream, warm brownie, roasted almonds, cashews, chocolate sauce, and caramel drizzle.",
  },
  
  // Sweets
  {
    id: "sw-1",
    name: "Kesar Rasmalai (2 Pcs)",
    category: "sweets",
    price: 140,
    approx_qty_gms: 180,
    description: "Spongy cottage cheese discs soaked in sweetened, thickened milk flavored with saffron and pistachios.",
  },
  {
    id: "sw-2",
    name: "Ghee Moong Dal Halwa",
    category: "sweets",
    price: 160,
    approx_qty_gms: 150,
    description: "Rich, slow-cooked dessert made with split green gram paste, clarified butter, sugar, and cardamoms.",
  },{
    id: "ds-3",
    name: "Gulab Jamun (2 Pcs)",
    category: "sweets",
    price: 120,
    approx_qty_gms: 180,
    description: "Soft and spongy khoya dumplings soaked in warm sugar syrup infused with cardamom and rose essence.",
  },
  {
    id: "ds-4",
    name: "Kulfi Falooda",
    category: "sweets",
    price: 190,
    approx_qty_gms: 280,
    description: "Traditional kulfi served with silky falooda sev, sweet basil seeds, rose syrup, and chilled milk.",
  },
  {
    id: "ds-5",
    name: "Hot Jalebi with Rabri",
    category: "sweets",
    price: 200,
    approx_qty_gms: 250,
    description: "Freshly fried crispy jalebis served with thick, creamy saffron-flavored rabri and garnished with dry fruits.",
  }
];
