# Generated by Django 5.0.14 on 2026-07-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menucategory_image_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ai_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='diet_type',
            field=models.CharField(default='Veg', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preferred_meal_type',
            field=models.CharField(default='Dinner', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preferred_mood',
            field=models.CharField(default='Happy', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='recommendation_boost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='spice_level',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='taste_type',
            field=models.CharField(default='Salty', max_length=50),
        ),
    ]
